--CREATE DATABASE [PRUEBA_TECNICA];
--USE PRUEBA_TECNICA;
-- -----------------------------------------------------
-- Table CAJA
-- -----------------------------------------------------
DROP TABLE IF EXISTS CAJA ;
CREATE TABLE CAJA (
  PK_CAJA INT IDENTITY (1,1) PRIMARY KEY,
  STICKER VARCHAR(45) NOT NULL UNIQUE,
  UBICACION VARCHAR(45) NOT NULL,
  ESTADO VARCHAR(45) NOT NULL,
  OBSERVACIONES VARCHAR(500) NOT NULL,
  FECHA_CREACION DATETIME,
  FECHA_MOVIMIENTO DATETIME
);
-- -----------------------------------------------------
-- Table BOLSA
-- -----------------------------------------------------
DROP TABLE IF EXISTS BOLSA;
CREATE TABLE  BOLSA (
  PK_BOLSA INT IDENTITY (1,1) PRIMARY KEY ,
  STICKER VARCHAR(45) NOT NULL UNIQUE,
  ESTADO VARCHAR(45) NOT NULL,
  FK_BOLSA_CAJA INT NOT NULL,
  CONSTRAINT FK_BOLSA_CAJA FOREIGN KEY (FK_BOLSA_CAJA) REFERENCES CAJA (PK_CAJA),  
  FECHA_INGRESO DATETIME,
  FECHA_MOVIMIENTO DATETIME
);
-- -----------------------------------------------------
-- Table CARPETA
-- -----------------------------------------------------
DROP TABLE IF EXISTS CARPETA ;
CREATE TABLE  CARPETA (
  PK_CARPETA INT IDENTITY (1,1) NOT NULL PRIMARY KEY ,
  STICKER VARCHAR(45) NOT NULL UNIQUE,
  FK_CARPETA_BOLSA INT NOT NULL,
  CONSTRAINT FK_CARPETA_BOLSA FOREIGN KEY (FK_CARPETA_BOLSA) REFERENCES BOLSA (PK_BOLSA),
  ESTADO VARCHAR(45) NOT NULL,
  ALETAS VARCHAR(45) NOT NULL,
  FECHA_INGRESO DATETIME,
  FECHA_MOVIMIENTO DATETIME
);
-- -----------------------------------------------------
-- Table DOCUMENTO
-- -----------------------------------------------------
DROP TABLE IF EXISTS DOCUMENTO ;
CREATE TABLE  DOCUMENTO (
  PK_DOCUMENTO INT IDENTITY (1,1) PRIMARY KEY,
  STICKER VARCHAR(45) NOT NULL UNIQUE,
  FK_DOCUMENTO_CARPETA INT NOT NULL,
  CONSTRAINT FK_DOCUMENTO_CARPETA FOREIGN KEY (FK_DOCUMENTO_CARPETA) REFERENCES CARPETA (PK_CARPETA),
  ESTADO VARCHAR(45) NOT NULL,
  FECHA_INGRESO DATETIME,
  FECHA_MOVIMIENTO DATETIME
);